name: Validate tags

on:
  create:
    tags:
      - "*"

permissions:
  contents: write
  issues: write

jobs:
  validate:
    uses: spearuav/org-wide-linting-configs/.github/workflows/validate-tags.yml@main
    secrets: inherit
